$myAutomationConnection = Get-AutomationConnection -Name AzureRunAsConnection
Connect-AzureRmAccount -CertificateThumbprint $myAutomationConnection.CertificateThumbprint -ApplicationId $myAutomationConnection.ApplicationId -ServicePrincipal -Tenant $myAutomationConnection.TenantId -Subscription $myAutomationConnection.SubscriptionId

$myAuzureContext = Set-AzureRmContext -Subscription $myAutomationConnection.SubscriptionId

$myLocalCred = Get-AutomationPSCredential -Name "myLocalCred"

Restart-Computer -ComputerName "myVm7476" -Credential $myLocalCred -Force 

# SIG # Begin signature block
# MIIFoAYJKoZIhvcNAQcCoIIFkTCCBY0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQURK+DuKoSgZrq4+h+dGVhDxn2
# D4ugggMqMIIDJjCCAg6gAwIBAgIQVVsKVE7lWIhAUZ8yyDASijANBgkqhkiG9w0B
# AQUFADArMSkwJwYDVQQDDCBteUh5YnJpZFdvcmtlclNpZ25pbmdDZXJ0aWZpY2F0
# ZTAeFw0xOTA4MjkxNTE3MDRaFw0yMDA4MjkxNTM3MDRaMCsxKTAnBgNVBAMMIG15
# SHlicmlkV29ya2VyU2lnbmluZ0NlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEF
# AAOCAQ8AMIIBCgKCAQEA3VKMUXQ/sf7PFQqvGaiCqfqE++asz4+JsoHPGzZh6xnc
# +e6O2qTtg1r39II1GcKJd4E6Hf3xGLcU0cSG6QHPyvkw53o3Z0RHF8frKyTXpLXb
# iIxzN5SXuhWb26z1BYUenJNBvRYNf9stWVa7+1NylNWYum/q0afefRleP0rcjrpy
# iruCtPFsfX/OvRbcmunk3TnHIqmA7Zg7A3TLrCfqHtHMLpeX7DZE7vHfbSDKa/7t
# H/IEeTbaunwQ1WzK8QFmZjyD+DPcH3NS3hYEpK8BLPd/QLnPFjqojrGAlSKPOJLs
# wyMjp6iPVB9HNNh95iNfbIDRvmS5unPlYWb+tElTDQIDAQABo0YwRDAOBgNVHQ8B
# Af8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFMxY3EAju3MD
# wa5nTSewaqCgTy+lMA0GCSqGSIb3DQEBBQUAA4IBAQCkfnowByayK2J8rYvwbYZD
# S2wqCsdBW4O5pXYGqEQT9BWGM9VrY5Y0r/pgTXbhoDAL4+SSxJprRih8NOd57c3M
# jKYuaXz+CzOSXvfqsCXVP65dJu9gkX/zvusv2EocEEJn45BJmNr4hm3idBDgPfWW
# 0h6pdwPZeuMJoVA0litPT0VjRnyhNTPcIHRvpzcO83Uasm2j0JvUh9cdSGEdi//t
# Kflax11+xueRR5cuVbDNw9akhkN8wJk0F0h4F78wlQDsLrzUQPv3wF1yjBpnB3nT
# wIHonJ57lF2Na83Y3JWrjxqCbK0T/DG/kqCXXHcS0J1Y03sr6eTT8NGc4UDhwHeI
# MYIB4DCCAdwCAQEwPzArMSkwJwYDVQQDDCBteUh5YnJpZFdvcmtlclNpZ25pbmdD
# ZXJ0aWZpY2F0ZQIQVVsKVE7lWIhAUZ8yyDASijAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUJTCK
# wNJIwEB7KA+yL3T30/kBxx4wDQYJKoZIhvcNAQEBBQAEggEAlTeyIKseMWMbqw6Y
# 0AYLG0cORpV4tNavE8QrmfEQKwOiBBmeBtf2OBN073h962YztyR7fN9UB5ldcT24
# cE7BBb6Va8hZESBYprvLV9ihFjvSLcObBmBlR6F1WmhhGHubm/WDPFKqyAinDNF3
# 2YZ/v7VYgZHN01T54yP7wMIYeqgvHiyYlV12RXmGKpziTFj0uCpCDLsHN3vf+z7O
# jDra/fK07h2FTpO2ziRFu5c6haEfMVhLpuEriDz8Zindd5j9+w1GFgmIWyXk/Jr6
# 8JDykTXmIZV0+ayZ2aHoJnaNVF35MkpNTKpZb0r9KyL9bXcIUc5rwrrPxFtZe9rH
# s2EgJQ==
# SIG # End signature block
