$myAutomationConnection = Get-AutomationConnection -Name AzureRunAsConnection
Connect-AzureRmAccount -CertificateThumbprint $myAutomationConnection.CertificateThumbprint -ApplicationId $myAutomationConnection.ApplicationId -ServicePrincipal -Tenant $myAutomationConnection.TenantId -Subscription $myAutomationConnection.SubscriptionId

$myAuzureContext = Set-AzureRmContext -Subscription $myAutomationConnection.SubscriptionId

$myLocalCred = Get-AutomationPSCredential -Name "myLocalCred"

Restart-Computer -ComputerName "myVm7476" -Credential $myLocalCred

# SIG # Begin signature block
# MIIFoAYJKoZIhvcNAQcCoIIFkTCCBY0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUTTkOS0mtzwGHEyNx7StGB6lM
# Xa6gggMqMIIDJjCCAg6gAwIBAgIQVVsKVE7lWIhAUZ8yyDASijANBgkqhkiG9w0B
# AQUFADArMSkwJwYDVQQDDCBteUh5YnJpZFdvcmtlclNpZ25pbmdDZXJ0aWZpY2F0
# ZTAeFw0xOTA4MjkxNTE3MDRaFw0yMDA4MjkxNTM3MDRaMCsxKTAnBgNVBAMMIG15
# SHlicmlkV29ya2VyU2lnbmluZ0NlcnRpZmljYXRlMIIBIjANBgkqhkiG9w0BAQEF
# AAOCAQ8AMIIBCgKCAQEA3VKMUXQ/sf7PFQqvGaiCqfqE++asz4+JsoHPGzZh6xnc
# +e6O2qTtg1r39II1GcKJd4E6Hf3xGLcU0cSG6QHPyvkw53o3Z0RHF8frKyTXpLXb
# iIxzN5SXuhWb26z1BYUenJNBvRYNf9stWVa7+1NylNWYum/q0afefRleP0rcjrpy
# iruCtPFsfX/OvRbcmunk3TnHIqmA7Zg7A3TLrCfqHtHMLpeX7DZE7vHfbSDKa/7t
# H/IEeTbaunwQ1WzK8QFmZjyD+DPcH3NS3hYEpK8BLPd/QLnPFjqojrGAlSKPOJLs
# wyMjp6iPVB9HNNh95iNfbIDRvmS5unPlYWb+tElTDQIDAQABo0YwRDAOBgNVHQ8B
# Af8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0OBBYEFMxY3EAju3MD
# wa5nTSewaqCgTy+lMA0GCSqGSIb3DQEBBQUAA4IBAQCkfnowByayK2J8rYvwbYZD
# S2wqCsdBW4O5pXYGqEQT9BWGM9VrY5Y0r/pgTXbhoDAL4+SSxJprRih8NOd57c3M
# jKYuaXz+CzOSXvfqsCXVP65dJu9gkX/zvusv2EocEEJn45BJmNr4hm3idBDgPfWW
# 0h6pdwPZeuMJoVA0litPT0VjRnyhNTPcIHRvpzcO83Uasm2j0JvUh9cdSGEdi//t
# Kflax11+xueRR5cuVbDNw9akhkN8wJk0F0h4F78wlQDsLrzUQPv3wF1yjBpnB3nT
# wIHonJ57lF2Na83Y3JWrjxqCbK0T/DG/kqCXXHcS0J1Y03sr6eTT8NGc4UDhwHeI
# MYIB4DCCAdwCAQEwPzArMSkwJwYDVQQDDCBteUh5YnJpZFdvcmtlclNpZ25pbmdD
# ZXJ0aWZpY2F0ZQIQVVsKVE7lWIhAUZ8yyDASijAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU7fbf
# b/4HakqHfyuFsd2IHntAfD0wDQYJKoZIhvcNAQEBBQAEggEADiKhkGE6dSWV+gaj
# VVYgNIYSvfwT5PWc7svoIAkEPwZHl2lYaXRSSYIBdEiq5xdswP2l/so8VSsxhmXV
# 3fcPNWAT7gUf5FlwhcbZPD3MJkfDyBrEYklMs9u9guzylmBIXxQJoxoTJUZCoAnm
# 6p1p3Im/xiio2K1RDlDrSUROVYg3ZKZ5Z7RI8tB3vvEmBt9HopU7ya16YKSrLXQs
# jducrQYKKOYgF6FJTyvbCGzZoz6uGWBuPg6Dcr6WIqtl9Q8eh6Qra/vUKpxc6P6H
# 27OGpCPur5/BqEpnAPV+osaUFLhUSltlOBdLteHpy3cIg6RRaQV29TezLCbY3oto
# 1EVtwQ==
# SIG # End signature block
